name: Continuous integration

on:
  push:
    branches-ignore:
      - "master"
      - "develop"
      - "release/**"
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.68.3'
      - name: Build
        run: |
          pushd custom-js
          npm ci
          npm run build
          popd
          hugo -b /docs --environment production